server:
  port: 8081

feign:
  hystrix:
    enabled: true

eureka:
  client:     #客户端注册进行eureka服务列表
    register-with-eureka: false
    service-url:
      #defaultZone: http://localhost:7001/eureka    #入驻的地址必须与7001 de faultZone地址一致
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/